# App configuration
server:
  port: 8189

# Spring
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.77.25:5432/postgresdb
    username: palandarus
    password: zx12gh67IP

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

