# App configuration
server:
  port: 8189

# Spring
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://77.37.134.139:5522/ravilich?schema=divisionOfExpenses
    username: ravilich
    password: Eiquemibi1oomied8d

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: divisionOfExpenses

